const titles={overview:"Overview",consultants:"Consultants",products:"Products",bookings:"Bookings",orders:"Orders",offers:"Offers",content:"Website CMS"};
const $=s=>document.querySelector(s);
async function api(path,opt={}){const r=await fetch(path,{headers:{"Content-Type":"application/json"},...opt});const d=await r.json();if(!r.ok)throw Error(d.error||"Request failed");return d}
function toast(t){const x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}
function go(id){document.querySelector('[data-tab="'+id+'"]').click()}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));$("#"+b.dataset.tab).classList.add("active");document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#pageTitle").textContent=titles[b.dataset.tab];loadTab(b.dataset.tab)});
async function loadTab(id){try{if(id==="overview")loadStats();if(id==="consultants")loadConsultants();if(id==="products")loadProducts();if(id==="bookings")loadBookings();if(id==="orders")loadOrders();if(id==="offers")loadOffers();if(id==="content")loadContent()}catch(e){toast(e.message)}}
async function loadStats(){const x=await api("/api/admin/stats");$("#mRevenue").textContent="₹"+Number(x.revenue).toLocaleString("en-IN");$("#mConsult").textContent=x.consultations;$("#mPrepaid").textContent=x.prepaidRate+"%";$("#mConversion").textContent=x.conversion+"%"}
function esc(x=""){return String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function loadConsultants(){const a=await api("/api/admin/consultants");$("#consultantList").innerHTML=a.map(x=>'<div class="consultant"><div class="avatar">'+esc(x.name.split(" ").map(v=>v[0]).join(""))+'</div><div><h3>'+esc(x.name)+'</h3><p>'+esc(x.type)+' · '+x.experience+'</p><small>★ '+x.rating+' · ₹'+x.price+' / 30 min</small></div><span class="pill">'+(x.available?"ACTIVE":"OFF")+'</span><button onclick="editConsultant(\''+x.id+'\')">Edit</button><button class="danger" onclick="removeItem(\'consultants\',\''+x.id+'\')">Delete</button></div>').join("")||'<div class="panel">No consultants yet.</div>'}
async function editConsultant(id){let x=id?await api("/api/admin/consultants"):null;if(id)x=x.find(v=>v.id===id);x=x||{name:"",type:"Vedic Astrologer",experience:"",price:899,rating:5,available:true,bio:""};modal("Consultant",x,async v=>{await api(id?"/api/admin/consultants/"+id:"/api/admin/consultants",{method:id?"PATCH":"POST",body:JSON.stringify({...v,price:Number(v.price),rating:Number(v.rating)})});closeModal();toast("Consultant saved");loadConsultants()})}
async function loadProducts(){const a=await api("/api/admin/products");$("#productList").innerHTML=a.map(x=>'<div class="product-row"><div class="product-icon">◇</div><div><h3>'+esc(x.name)+'</h3><small>'+esc(x.category)+' · Stock: '+x.stock+'</small></div><b>₹'+x.price+'</b><button onclick="editProduct(\''+x.id+'\')">Edit</button><button class="danger" onclick="removeItem(\'products\',\''+x.id+'\')">Delete</button></div>').join("")||'<div class="panel">No products yet.</div>'}
async function editProduct(id){let x=id?await api("/api/admin/products"):null;if(id)x=x.find(v=>v.id===id);x=x||{name:"",slug:"",category:"",description:"",price:999,compareAt:"",stock:0,active:true};modal("Product",x,async v=>{await api(id?"/api/admin/products/"+id:"/api/admin/products",{method:id?"PATCH":"POST",body:JSON.stringify({...v,price:Number(v.price),compareAt:Number(v.compareAt||0),stock:Number(v.stock)})});closeModal();toast("Product saved");loadProducts()})}
async function loadBookings(){const a=await api("/api/admin/bookings");$("#bookingRows").innerHTML=a.map(x=>'<tr><td>'+x.id+'</td><td>'+esc(x.customerName)+'<br><small>'+esc(x.customerPhone)+'</small></td><td>'+esc(x.concern)+'</td><td>'+esc(x.consultantId)+'</td><td>'+esc(x.slot)+'</td><td>₹'+x.amount+'</td><td><select onchange="updateStatus(\'bookings\',\''+x.id+'\',this.value)"><option '+(x.status==="PENDING_PAYMENT"?"selected":"")+'>PENDING_PAYMENT</option><option '+(x.status==="CONFIRMED"?"selected":"")+'>CONFIRMED</option><option '+(x.status==="COMPLETED"?"selected":"")+'>COMPLETED</option><option '+(x.status==="CANCELLED"?"selected":"")+'>CANCELLED</option></select></td></tr>').join("")||'<tr><td colspan="7">No bookings yet.</td></tr>'}
async function loadOrders(){const a=await api("/api/admin/orders");$("#orderRows").innerHTML=a.map(x=>'<tr><td>'+x.id+'</td><td>'+esc(x.customerName)+'</td><td>'+x.fulfillment+'</td><td>₹'+x.total+'</td><td>'+x.status+'</td><td><select onchange="updateStatus(\'orders\',\''+x.id+'\',this.value)"><option>PAYMENT_PENDING</option><option>CONFIRMATION_PENDING</option><option>CONFIRMED</option><option>PACKED</option><option>SHIPPED</option><option>DELIVERED</option><option>RTO</option><option>CANCELLED</option></select></td></tr>').join("")||'<tr><td colspan="6">No orders yet.</td></tr>'}
async function updateStatus(type,id,status){await api("/api/admin/"+type+"/"+id,{method:"PATCH",body:JSON.stringify({status})});toast("Status updated")}
async function loadOffers(){const a=await api("/api/admin/offers");$("#offerList").innerHTML=a.map(x=>'<div class="offer"><b>'+esc(x.code)+'</b><span>'+esc(x.title)+'</span><em>'+(x.active?"ACTIVE":"PAUSED")+'</em><button onclick="editOffer(\''+x.id+'\')">Edit</button><button class="danger" onclick="removeItem(\'offers\',\''+x.id+'\')">Delete</button></div>').join("")}
async function editOffer(id){let x=id?await api("/api/admin/offers"):null;if(id)x=x.find(v=>v.id===id);x=x||{code:"",title:"",type:"FIXED",value:100,active:true};modal("Offer",x,async v=>{await api(id?"/api/admin/offers/"+id:"/api/admin/offers",{method:id?"PATCH":"POST",body:JSON.stringify({...v,value:Number(v.value),active:v.active==="true"||v.active===true})});closeModal();toast("Offer saved");loadOffers()})}
async function removeItem(type,id){if(!confirm("Delete this item?"))return;await api("/api/admin/"+type+"/"+id,{method:"DELETE"});toast("Deleted");type==="consultants"?loadConsultants():type==="products"?loadProducts():loadOffers()}
async function loadContent(){const x=await api("/api/admin/content");["heroTitle","heroSubtitle","announcement","seoTitle","seoDescription"].forEach(k=>$("#"+k).value=x[k]||"")}
async function saveContent(){const x={};["heroTitle","heroSubtitle","announcement","seoTitle","seoDescription"].forEach(k=>x[k]=$("#"+k).value);await api("/api/admin/content",{method:"PATCH",body:JSON.stringify(x)});toast("Website content published")}
function closeModal(){$("#adminModal").innerHTML=""}
function modal(title,x,save){$("#adminModal").innerHTML='<div class="modal"><div class="editor"><button class="modal-x" onclick="closeModal()">×</button><small>CMS EDITOR</small><h2>'+title+'</h2><div class="editor-fields">'+Object.entries(x).filter(([k])=>k!=="id"&&k!=="slug").map(([k,v])=><label>'+k+'<input data-k="'+k+'" value="'+esc(v)+'"></label>').join("")+'</div><button class="primary" id="saveBtn">Save changes</button></div></div>';$("#saveBtn").onclick=()=>{const v={};document.querySelectorAll("[data-k]").forEach(i=>v[i.dataset.k]=i.value);save(v)}}
loadStats();
